### ISSUE TITLE
Saman palvelun lisääminen varaukseen uudestaan antaa väärän virheilmoituksen

### ISSUE THREAD

**Issue by Anssoh** [jounikuj/mokkivaraus#56]
Lisättäessä varaukseen palvelua, joka on jo varauksessa, tulostuvassa viesti-ikkunassa lukee "Muista valita palvelun rivi, jonka haluat lisätä varaukseen." Tämä ei liity virheeseen.

Sopiva viesti olisi esimerkiksi "Et voi lisätä varaukseen jo liitettyä palvelua uudestaan. Jos haluat muuttaa palvelun määrää, poista palvelu varauksesta ja lisää se sen jälkeen uudestaan."

**Comment by ilaripesonen** [comment]
Uusimmassa masterissa tämä on hoidettu sillä, että varauksen päivämäärien kanssa risteäviä jo varattuja palveluita ei voi lisätä varaukseen.
