### ISSUE TITLE
Mökkien lisäys varaukseen antaa väärän lukumäärän

### ISSUE THREAD

**Issue by Anssoh** [jounikuj/mokkivaraus#57]
Lisättäessä mökkipalveluja (tyyppi 1) varaukseen 2, lisättävä määrä on automaattisesti 7 eikä sitä voi muuttaa. 

Jos lisätään uusi varaus tiedoilla:
Asiakas ID: 4
Toimipiste: Tampere
Varauksen alkupvm: 20.5.2018
Varauksen loppupvm: 23.5.2018
Vahvistuspäivämäärä: 20.5.2018

Lisättävän mökkipalvelu luotuun varaukseen lukumäärä on automaattisesti 3.

Vaikuttaisi olevan yhteys alku- ja loppupäivämäärään.

**Comment by ilaripesonen** [comment]
Tämä lisättiin, kun laskussa lasketaan pelkästään palvelun lkm * hinta (ja vero) eikä siellä erikseen katsottu varauksen päivämääriä ja kuinka pitkään mökki on varattu. Yksi mökki olisi voinut olla esimerkiksi puoli vuotta varauksessa sillä yhden mökin lkm-hinnalla.
