### ISSUE TITLE
Ylläpidosta avautuvia ikkunoita voi avata useita yhtäaikaisesti.

### ISSUE THREAD

**Issue by Anssoh** [jounikuj/mokkivaraus#59]
Ylläpitoikkunan Muokkaa toimipistettä, Lisää palvelu ja Muokkaa palvelua -ikkunoita voi avata useita yhtäaikaisesti.

Lisää toimipiste -ikkunoita voi avata kerrallaan vain yhden.

Voisiko ylläpitoikkunan jäädyttää kun lisäys- tai muokkausikkuna on auki, kunnes siinä valitaan Ok tai Peruuta? Poistaisi myös mahdollisuuden, että ikkunoita jää leijumaan, jos ylläpitoikkuna suljetaan kun lisäys- tai muokkausikkunoita on vielä auki.

**Comment by ilaripesonen** [comment]
branchissa lisätty ominaisuus, että Ylläpito-ikkuna jäädytetään kun avataan näitä ali-ikkunoita

**Comment by ilaripesonen** [comment]
branch mergattu
