### ISSUE TITLE
Lisää toimipiste täyttää edellisen tiedot automaattisesti

### ISSUE THREAD

**Issue by Anssoh** [jounikuj/mokkivaraus#60]
Lisättäessä peräkkäin kaksi toimipistettä, ensimmäisen lisätyn toimipisteen tiedot täyttyvät automaattisesti seuraavan toimipisteen lisäysikkunaan.

Samaa ei tapahdu palvelujen lisäyksessä.

**Comment by ilaripesonen** [comment]
muutokset tehty branchiin, ei vielä mergattu

**Comment by ilaripesonen** [comment]
branch mergattu
