### ISSUE TITLE
Varausikkunasta avautuu väärä välilehti

### ISSUE THREAD

**Issue by Anssoh** [jounikuj/mokkivaraus#62]
Avattaessa varausikkuna asiakasikkunan "Tarkastele asiakkaan varauksia" -painikkeella avautuu "Varauksen palvelut" -välilehti, jos varausikkuna on saman istunnon aikana avattu ja suljettu välilehden ollessa avattuna.

1. Avaa varausikkuna ja "varauksen palvelut" -välilehti
2. Sulje varausikkuna
3. Avaa asiakasikkuna
4. Valitse asiakas
5. Valitse "Tarkastele asiakkaan varauksia."

**Comment by Ilaripo** [comment]
Fixed
